[package]
name = "bipolar-orchestrator"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bipolar-orchestrator"
path = "src/main.rs"

[dependencies]
common-game = "3.0.0"
crossbeam-channel = "0.5"
log = "0.4"
env_logger = "0.11"
rand = "0.10.1"

# External planet repos (uncomment as each factory file is filled in)
#
# orbitron           = { git = "https://github.com/Advanced-Programming-2025-Orbitron/Orbitron" }
# skycartel          = { git = "https://github.com/0TH08/RustyPlanets", branch = "type-a-ai-cleanup" }
# rustrelli          = { git = "https://github.com/Rustrelli/rustrelli" }
# thecompilerstrikesback = { git = "https://github.com/TheCompilerStrikesBackAP2025/TheCompilerStrikesBack" }
# crabtorio          = { git = "https://github.com/crabtorio/crabtorio" }
# houstonwehaveaborrow = { git = "https://github.com/Houston-we-have-a-borrow/Planet" }
# enterprise         = { git = "https://github.com/Thompspsps/Enterprise_planet" }

[dev-dependencies]
